version: "3.8"

services:
  database:
    image: postgres:13.0-alpine
    container_name: delivery_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    container_name: delivery_web
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/delivery
    links:
      - database
    depends_on:
      - database
volumes:
  postgres:
    driver: local
